[tool.mypy]
python_version = "3.10"
plugins = [
    "numpy.typing.mypy_plugin",
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main",
]
exclude = [
    "venv/"
]
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "ClosestColour.settings"

[tool.black]
line-length = 120
target-version = ["py310"]
extend-exclude = "^/venv/"

[tool.isort]
profile = "black"
skip = "venv"

[tool.pytest.ini_options]
testpaths = ["tests"]
DJANGO_SETTINGS_MODULE = "ClosestColour.settings"
